import os
import sys
from pathlib import Path


MODEL_SIZES = (
    "yolox_nano",
    "yolox_tiny",
    "yolox_s",
    "yolox_m",
    "yolox_l",
    "yolox_x",
)

EXP_MODULES = {
    "yolox_nano": "exps.default.yolox_nano",
    "yolox_tiny": "exps.default.yolox_tiny",
    "yolox_s": "exps.default.yolox_s",
    "yolox_m": "exps.default.yolox_m",
    "yolox_l": "exps.default.yolox_l",
    "yolox_x": "exps.default.yolox_x",
}

EXP_FILES = {
    model_size: Path(*module.split(".")).with_suffix(".py")
    for model_size, module in EXP_MODULES.items()
}


def repo_root() -> Path:
    return Path(__file__).resolve().parents[3]


def src_root() -> Path:
    return repo_root() / "src"


def vendor_yolox_root() -> Path:
    return src_root() / "yolox_gui" / "vendor" / "yolox"


def third_party_yolox_root() -> Path:
    return repo_root() / "third_party" / "YOLOX"


def yolox_root() -> Path:
    vendor = vendor_yolox_root()
    if vendor.exists():
        return vendor
    return third_party_yolox_root()


def weights_root() -> Path:
    return repo_root() / "weights" / "yolox"


def validate_model_size(model_size: str) -> str:
    if model_size not in MODEL_SIZES:
        raise ValueError(f"Unsupported YOLOX model size: {model_size}")
    return model_size


def resolve_exp_file(model_size: str) -> Path:
    validate_model_size(model_size)
    exp_file = yolox_root() / EXP_FILES[model_size]
    if not exp_file.exists():
        raise FileNotFoundError(f"YOLOX exp file was not found: {exp_file}")
    return exp_file


def ensure_yolox_root() -> Path:
    root = yolox_root()
    if not (root / "yolox").exists():
        raise FileNotFoundError(
            "YOLOX vendor code was not found. Expected src/yolox_gui/vendor/yolox/yolox."
        )
    return root


def add_yolox_to_syspath() -> Path:
    root = ensure_yolox_root()
    root_text = str(root)
    if root_text not in sys.path:
        sys.path.insert(0, root_text)
    return root


def yolox_subprocess_env() -> dict:
    root = ensure_yolox_root()
    env = os.environ.copy()
    existing = env.get("PYTHONPATH", "")
    entries = [str(root), str(src_root())]
    if existing:
        entries.append(existing)
    env["PYTHONPATH"] = os.pathsep.join(entries)
    return env


def infer_checkpoint_num_classes(checkpoint_path) -> int:
    checkpoint = Path(checkpoint_path)
    if not checkpoint.exists():
        raise FileNotFoundError(f"Checkpoint was not found: {checkpoint}")

    import torch

    data = torch.load(str(checkpoint), map_location="cpu")
    state = data.get("model", data) if isinstance(data, dict) else data
    if not isinstance(state, dict):
        raise ValueError(f"Unsupported checkpoint format: {checkpoint}")

    for key, value in state.items():
        if key.endswith("head.cls_preds.0.weight") or ".cls_preds.0.weight" in key:
            return int(value.shape[0])
    for key, value in state.items():
        if "cls_preds" in key and key.endswith(".weight") and hasattr(value, "shape"):
            return int(value.shape[0])
    raise ValueError(
        "Could not infer the number of classes from the YOLOX checkpoint. "
        "Expected head.cls_preds.*.weight tensors."
    )


def find_class_names(checkpoint_path, num_classes: int) -> list[str]:
    checkpoint = Path(checkpoint_path)
    candidates = [
        checkpoint.parent / "classes.txt",
        checkpoint.parent.parent / "classes.txt",
        checkpoint.with_suffix(".classes.txt"),
    ]
    for path in candidates:
        if path.exists():
            names = [line.strip() for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]
            if names:
                if len(names) < num_classes:
                    names.extend(f"class_{idx}" for idx in range(len(names), num_classes))
                return names[:num_classes]

    if num_classes == 80:
        add_yolox_to_syspath()
        try:
            from yolox.data.datasets import COCO_CLASSES

            return list(COCO_CLASSES)
        except Exception:
            pass
    return [f"class_{idx}" for idx in range(num_classes)]


def create_runtime_exp_file(
    *,
    model_size: str,
    output_dir,
    exp_name: str,
    num_classes: int,
    img_size: int,
    target_path,
    dataset_dir=None,
    epochs: int | None = None,
) -> Path:
    validate_model_size(model_size)
    target = Path(target_path)
    target.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Generated by YOLOX-train-detection-GUI.",
        "import os",
        f"from {EXP_MODULES[model_size]} import Exp as BaseExp",
        "",
        "",
        "class Exp(BaseExp):",
        "    def __init__(self):",
        "        super().__init__()",
        f"        self.exp_name = {exp_name!r}",
        f"        self.output_dir = {str(Path(output_dir).resolve())!r}",
        f"        self.num_classes = {int(num_classes)}",
        f"        self.input_size = ({int(img_size)}, {int(img_size)})",
        f"        self.test_size = ({int(img_size)}, {int(img_size)})",
        "        self.data_num_workers = 2",
        "        self.print_interval = 10",
        "        self.eval_interval = 1",
    ]
    if epochs is not None:
        lines.append(f"        self.max_epoch = {int(epochs)}")
        lines.append("        self.save_history_ckpt = False")
    if dataset_dir is not None:
        lines.extend(
            [
                f"        self.data_dir = {str(Path(dataset_dir).resolve())!r}",
                "        self.train_ann = 'instances_train2017.json'",
                "        self.val_ann = 'instances_val2017.json'",
            ]
        )
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return target

