TEXT = {
    "ja": {
        "app_title": "YOLOX Train and Detect",
        "app_badge": "YOLOX training / inference / ONNX export",
        "nav_train": "学習",
        "nav_detect": "推論（画像/動画）",
        "nav_camera": "推論（カメラ）",
        "nav_export": "Model Export",
        "language": "言語",
        "appearance": "表示",
        "light": "ライト",
        "dark": "ダーク",
        "scale": "倍率",
        "scale_placeholder": "100",
        "apply": "適用",
        "ready": "待機中",
        "busy": "処理中",
        "blocked": "処理中は画面を切り替えられません。",
        "not_selected": "未選択",
        "browse": "選択",
        "open_model": "モデル一覧",
        "details": "詳細",
        "path_details": "選択中のパス",
        "train_title": "YOLOX Model Training",
        "train_subtitle": "YOLO形式データセットをCOCO形式へ変換し、YOLOXで学習します。",
        "device": "実行デバイス",
        "gpu_ready": "GPU ready",
        "cpu_only": "CPU only",
        "project_name": "プロジェクト名",
        "project_placeholder": "例: duck_detection_001",
        "train_data": "学習データフォルダ",
        "save_folder": "学習結果の保存先",
        "yolo_model": "YOLOX model size",
        "input_size": "入力サイズ",
        "input_size_placeholder": "例: 640",
        "epochs": "エポック数",
        "epochs_placeholder": "例: 100",
        "batch": "バッチサイズ",
        "batch_placeholder": "例: 16",
        "classes": "クラス名",
        "classes_hint": "1行に1クラス",
        "start_training": "学習開始",
        "training_click_stop": "学習中（クリックで停止）",
        "stopping_training": "停止中...",
        "train_stopped": "学習を停止しました。",
        "log_title": "学習ログ",
        "eta": "残り時間",
        "eta_unknown": "計算中",
        "elapsed": "経過",
        "progress_idle": "未開始",
        "progress_running": "学習中",
        "progress_done": "完了",
        "progress_failed": "失敗",
        "progress_stopped": "停止",
        "missing_title": "設定が不足しています",
        "invalid_title": "設定を確認してください",
        "missing_prefix": "次の項目を設定してください。",
        "invalid_number": "入力サイズ、エポック数、バッチサイズは正の整数で入力してください。",
        "invalid_project": "プロジェクト名は英数字、ハイフン、アンダースコアのみ使えます。",
        "train_started": "YOLOX学習を開始しました。",
        "train_done": "YOLOX学習が完了しました。",
        "train_failed": "YOLOX学習に失敗しました。ログを確認してください。",
        "detect_title": "YOLOX Image/Video Inference",
        "detect_subtitle": "フォルダ内の画像と動画にYOLOX推論を実行し、resultsフォルダへ保存します。",
        "media_folder": "画像/動画フォルダ",
        "model_file": "YOLOX checkpoint (.pth/.pt)",
        "confidence": "Confidence threshold",
        "confidence_placeholder": "0.5",
        "nms": "NMS threshold",
        "nms_placeholder": "0.45",
        "invalid_confidence": "しきい値は0.01から1.0の範囲で入力してください。",
        "start_detection": "推論開始",
        "preview": "プレビュー",
        "previous": "前へ",
        "next": "次へ",
        "left_right_hint": "Left / Right キーで移動",
        "detect_running": "推論中",
        "detect_done": "推論が完了しました。",
        "detect_failed": "推論に失敗しました。",
        "no_results": "表示できる結果画像がありません。",
        "camera_title": "YOLOX Camera Inference",
        "camera_subtitle": "リアルタイム推論を行い、Enterで現在フレームを保存します。",
        "camera_device": "カメラデバイス",
        "camera_refresh": "再読込",
        "no_camera_device": "使用できるカメラが見つかりません。",
        "camera_save": "保存先フォルダ",
        "start": "START",
        "stop": "STOP",
        "enter_hint": "Enter: 保存",
        "esc_hint": "Esc: 停止",
        "camera_running": "カメラ推論中",
        "camera_stopped": "停止しました。",
        "capture_done": "保存しました。",
        "capture_failed": "保存できませんでした。保存先とカメラ状態を確認してください。",
        "error": "エラー",
        "info": "情報",
        "select_yolo_model": "YOLOX Model Sizeを選択",
        "all_models": "すべてのファイル",
        "file_model_filter": "YOLOX checkpoint",
        "export_title": "Model Format Conversion",
        "export_subtitle": "YOLOX checkpointをONNXへ変換します。",
        "checkpoint_file": "Input checkpoint path",
        "output_onnx": "Output ONNX path",
        "opset": "Opset version",
        "opset_placeholder": "11",
        "simplify": "Simplify",
        "dynamic_axes": "Dynamic axes",
        "export_onnx": "Export ONNX",
        "export_running": "ONNX export running",
        "export_done": "ONNX export completed.",
        "export_failed": "ONNX export failed.",
        "todo_not_implemented": "TODO: not implemented yet.",
        "select_checkpoint": "Select checkpoint",
        "select_output_onnx": "Select ONNX output",
    },
    "en": {
        "app_title": "YOLOX Train and Detect",
        "app_badge": "YOLOX training / inference / ONNX export",
        "nav_train": "Train",
        "nav_detect": "Inference (Image/Video)",
        "nav_camera": "Inference (Camera)",
        "nav_export": "Model Export",
        "language": "Language",
        "appearance": "Appearance",
        "light": "Light",
        "dark": "Dark",
        "scale": "Scale",
        "scale_placeholder": "100",
        "apply": "Apply",
        "ready": "Ready",
        "busy": "Busy",
        "blocked": "Navigation is locked while a job is running.",
        "not_selected": "Not selected",
        "browse": "Select",
        "open_model": "Model list",
        "details": "Details",
        "path_details": "Selected path",
        "train_title": "YOLOX Model Training",
        "train_subtitle": "Convert YOLO-label datasets to COCO format and train with YOLOX.",
        "device": "Device",
        "gpu_ready": "GPU ready",
        "cpu_only": "CPU only",
        "project_name": "Project name",
        "project_placeholder": "e.g. duck_detection_001",
        "train_data": "Training data folder",
        "save_folder": "Training output folder",
        "yolo_model": "YOLOX model size",
        "input_size": "Input size",
        "input_size_placeholder": "e.g. 640",
        "epochs": "Epochs",
        "epochs_placeholder": "e.g. 100",
        "batch": "Batch size",
        "batch_placeholder": "e.g. 16",
        "classes": "Class names",
        "classes_hint": "One class per line",
        "start_training": "Start Training",
        "training_click_stop": "Training (click to stop)",
        "stopping_training": "Stopping...",
        "train_stopped": "Training stopped.",
        "log_title": "Training Log",
        "eta": "ETA",
        "eta_unknown": "Calculating",
        "elapsed": "Elapsed",
        "progress_idle": "Idle",
        "progress_running": "Training",
        "progress_done": "Done",
        "progress_failed": "Failed",
        "progress_stopped": "Stopped",
        "missing_title": "Missing settings",
        "invalid_title": "Check settings",
        "missing_prefix": "Please set the following items.",
        "invalid_number": "Input size, epochs, and batch size must be positive integers.",
        "invalid_project": "Project name can contain only letters, numbers, hyphens, and underscores.",
        "train_started": "YOLOX training started.",
        "train_done": "YOLOX training completed.",
        "train_failed": "YOLOX training failed. Check the log.",
        "detect_title": "YOLOX Image/Video Inference",
        "detect_subtitle": "Run YOLOX inference on images and videos in a folder and save outputs to results.",
        "media_folder": "Image/video folder",
        "model_file": "YOLOX checkpoint (.pth/.pt)",
        "confidence": "Confidence threshold",
        "confidence_placeholder": "0.5",
        "nms": "NMS threshold",
        "nms_placeholder": "0.45",
        "invalid_confidence": "Threshold values must be between 0.01 and 1.0.",
        "start_detection": "Start Detection",
        "preview": "Preview",
        "previous": "Previous",
        "next": "Next",
        "left_right_hint": "Use Left / Right to move",
        "detect_running": "Detecting",
        "detect_done": "Detection completed.",
        "detect_failed": "Detection failed.",
        "no_results": "No result images to display.",
        "camera_title": "YOLOX Camera Inference",
        "camera_subtitle": "Run live inference and press Enter to save the current frame.",
        "camera_device": "Camera device",
        "camera_refresh": "Refresh",
        "no_camera_device": "No available camera was found.",
        "camera_save": "Save folder",
        "start": "START",
        "stop": "STOP",
        "enter_hint": "Enter: Capture",
        "esc_hint": "Esc: Stop",
        "camera_running": "Camera running",
        "camera_stopped": "Stopped.",
        "capture_done": "Saved.",
        "capture_failed": "Could not save. Check the save folder and camera status.",
        "error": "Error",
        "info": "Info",
        "select_yolo_model": "Select YOLOX Model Size",
        "all_models": "All files",
        "file_model_filter": "YOLOX checkpoint",
        "export_title": "Model Format Conversion",
        "export_subtitle": "Convert a YOLOX checkpoint to ONNX.",
        "checkpoint_file": "Input checkpoint path",
        "output_onnx": "Output ONNX path",
        "opset": "Opset version",
        "opset_placeholder": "11",
        "simplify": "Simplify",
        "dynamic_axes": "Dynamic axes",
        "export_onnx": "Export ONNX",
        "export_running": "ONNX export running",
        "export_done": "ONNX export completed.",
        "export_failed": "ONNX export failed.",
        "todo_not_implemented": "TODO: not implemented yet.",
        "select_checkpoint": "Select checkpoint",
        "select_output_onnx": "Select ONNX output",
    },
}

